// @vitest-environment jsdom
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup,act} from '@testing-library/react';
import type {Snapshot} from './types';
const mock=vi.hoisted(()=>({snapshot:vi.fn(),action:vi.fn(),save:vi.fn(),listener:()=>{}}));
vi.mock('./api',()=>({view:'main',api:{snapshot:mock.snapshot,action:mock.action,save:mock.save,subscribe:(fn:()=>void)=>{mock.listener=fn;return ()=>{}}}}));
import {App} from './App';
const attachment={id:'file1',name:'important.txt',path:'/work/important.txt',mime:'text/plain'};
function state(id='a',version=1):Snapshot{return {version,currentId:id,current:{id,title:'会话 '+id,pinned:false,cwd:'/work',createdAt:'',updatedAt:'',status:'idle',error:'',draft:'',messages:[],queue:[],interaction:null,models:[],model:'',commands:[]},sessions:[],settings:{shortcut:'Alt+Space',piPath:''},environment:{piPath:'/bin/pi',version:'0.84.1',available:true,error:''},error:''}}
beforeEach(()=>{vi.resetAllMocks();Element.prototype.scrollIntoView=vi.fn();mock.snapshot.mockResolvedValue(state());mock.action.mockResolvedValue(state('a',2))});
afterEach(()=>cleanup());
async function setup(s=state()){mock.snapshot.mockResolvedValue(s);render(<App/>);return await screen.findByRole('textbox',{name:'消息'})}
it('独立验收：移除已持久化附件后保存空附件列表',async()=>{const s=state();s.current!.draftAttachments=[attachment];await setup(s);fireEvent.click(screen.getByRole('button',{name:'移除 important.txt'}));await waitFor(()=>expect(mock.action).toHaveBeenCalledWith('draft',expect.objectContaining({id:'a',attachments:[]})),{timeout:1500});});
it('独立验收：草稿持久化等待期间切换会话不会把 B 内容投给 A',async()=>{let resolve!:(s:Snapshot)=>void;mock.action.mockImplementation((action)=>action==='draft'?new Promise(r=>{resolve=r}):Promise.resolve(state('b',4)));const input=await setup();fireEvent.change(input,{target:{value:'A 的问题'}});await waitFor(()=>expect(mock.action).toHaveBeenCalledWith('draft',expect.anything()),{timeout:1500});fireEvent.click(screen.getByRole('button',{name:/^发送/}));const b=state('b',3);b.current!.draft='B 的私有问题';mock.snapshot.mockResolvedValue(b);await act(async()=>mock.listener());await act(async()=>resolve(state('a',2)));const sends=mock.action.mock.calls.filter(c=>c[0]==='send');expect(sends.every(c=>c[1].id!=='a'||c[1].text==='A 的问题')).toBe(true);});
it('独立验收：原始 HTML和危险协议不执行，远程图片按新需求展示且不发送来源页',async()=>{const s=state();s.current!.messages=[{id:'m',role:'assistant',text:'<script>alert(1)</script>\n\n[危险](javascript:alert%281%29) ![追踪](https://tracker.invalid/pixel) [报告](report%20one.md)',status:'complete',createdAt:'',attachments:[]}];const {container}=render(<App/>);mock.snapshot.mockResolvedValue(s);await act(async()=>mock.listener());await screen.findByText('报告');expect(container.querySelector('script')).toBeNull();expect(container.querySelector('.messages img')?.getAttribute('referrerpolicy')).toBe('no-referrer');fireEvent.click(screen.getByText('危险'));expect(mock.action).not.toHaveBeenCalled();fireEvent.click(screen.getByText('报告'));expect(mock.action).toHaveBeenCalledWith('openFile',{path:'/work/report one.md',sessionId:'a'});});
it('独立验收：缺失 Pi 有安装和重新检测入口，禁用发送按钮',async()=>{const s=state();s.environment.available=false;await setup(s);fireEvent.change(screen.getByRole('textbox',{name:'消息'}),{target:{value:'test'}});expect((screen.getByRole('button',{name:/^发送/}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'安装与配置指南 ↗'}));expect(mock.action).toHaveBeenCalledWith('openURL',expect.anything());});
it('独立验收：历史搜索匹配正文且置顶优先，选择携带正确会话',async()=>{const s=state();const a={...s.current!,title:'Alpha',searchableText:'关键内容',updatedAt:'2026-09-09'};const b={...a,id:'b',title:'Beta',pinned:true,updatedAt:'2025-01-01'};s.sessions=[a,b];await setup(s);const entries=screen.getAllByRole('button').filter(e=>e.className==='session-select');expect(entries.map(e=>e.textContent)).toEqual(['⌃ Beta准备就绪','Alpha准备就绪']);fireEvent.change(screen.getByRole('textbox',{name:'搜索历史会话'}),{target:{value:'关键内容'}});expect(screen.getAllByRole('button').filter(e=>e.className==='session-select')).toHaveLength(2);fireEvent.click(entries[0]);await waitFor(()=>expect(mock.action).toHaveBeenCalledWith('select',{id:'b'}));});
it('独立验收：Shift Enter 保留换行行为，不触发发送',async()=>{const input=await setup();fireEvent.change(input,{target:{value:'两行'}});fireEvent.keyDown(input,{key:'Enter',shiftKey:true});expect(mock.action).not.toHaveBeenCalled();});
it('独立验收：同名模型跨 Provider 可以分别选中',async()=>{const s=state();s.current!.models=[{id:'shared-model',name:'供应方 A',provider:'a'},{id:'shared-model',name:'供应方 B',provider:'b'}];s.current!.model='shared-model';await setup(s);const option=screen.getByRole('option',{name:'供应方 B'}) as HTMLOptionElement;fireEvent.change(screen.getByRole('combobox',{name:'模型'}),{target:{value:option.value}});expect(mock.action).toHaveBeenCalledWith('model',expect.objectContaining({provider:'b',id:'shared-model'}));});
it('独立验收：上传期间切换会话仍保存原会话文字和附件',async()=>{const s=state();s.current!.draft='已保存的原问题';let resolve!:(a:typeof attachment)=>void;mock.save.mockImplementation(()=>new Promise(r=>{resolve=r}));await setup(s);const file={name:'important.txt',size:4,type:'text/plain',arrayBuffer:async()=>new TextEncoder().encode('test').buffer};fireEvent.drop(screen.getByRole('textbox',{name:'消息'}),{dataTransfer:{files:[file]}});await waitFor(()=>expect(mock.save).toHaveBeenCalled());mock.snapshot.mockResolvedValue(state('b',3));await act(async()=>mock.listener());await act(async()=>resolve(attachment));await waitFor(()=>expect(mock.action).toHaveBeenCalledWith('draft',expect.objectContaining({id:'a',text:'已保存的原问题',attachments:[attachment]})),{timeout:1500});const again=state('a',5);again.current!.draft='已保存的原问题';mock.snapshot.mockResolvedValue(again);await act(async()=>mock.listener());expect((screen.getByRole('textbox',{name:'消息'}) as HTMLTextAreaElement).value).toBe('已保存的原问题');});
it('独立验收：插入队列绑定展示会话和消息 ID',async()=>{const s=state();s.current!.status='running';s.current!.queue=[{id:'q1',role:'user',text:'补充',status:'queued',createdAt:'',attachments:[]}];await setup(s);fireEvent.click(screen.getByRole('button',{name:'立即插入'}));expect(mock.action).toHaveBeenCalledWith('insert',{sessionId:'a',messageId:'q1'});});
it('独立验收：Pi 可执行但没有模型时仍提供配置指南',async()=>{const s=state();s.current!.modelsState='ready';await setup(s);expect(screen.getByText(/Pi 已安装。请检查 Pi 的模型配置/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'配置指南 ↗'}));expect(mock.action).toHaveBeenCalledWith('openURL',expect.objectContaining({url:expect.stringMatching(/^https:/)}));});
