// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "./internal/core/models.js";

export function Action(view: string, action: string, p: { [_ in string]?: any } | null): $CancellablePromise<core$0.Snapshot> {
    return $Call.ByID(1549377734, view, action, p);
}

export function SaveAttachment(name: string, mime: string, data: string): $CancellablePromise<core$0.Attachment> {
    return $Call.ByID(1566121172, name, mime, data);
}

export function Snapshot(view: string): $CancellablePromise<core$0.Snapshot> {
    return $Call.ByID(2571221232, view);
}
