// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Attachment {
    "id": string;
    "name": string;
    "path": string;
    "mime": string;
    "preview"?: string;
}

export interface Command {
    "name": string;
    "description": string;
    "source": string;
}

export interface Environment {
    "piPath": string;
    "version": string;
    "available": boolean;
    "error": string;
}

export interface Interaction {
    "id": string;
    "method": string;
    "title": string;
    "options": string[] | null;
    "message": string;
    "defaultValue": string;
}

export interface Message {
    "agentKey"?: string;
    "id": string;
    "role": string;
    "text": string;
    "status": string;
    "createdAt": string;
    "attachments": Attachment[] | null;
}

export interface Model {
    "id": string;
    "name": string;
    "provider": string;
}

export interface Session {
    "draftOnly": boolean;
    "cwdSource"?: string;
    "managedWorkspace": boolean;
    "draftRevision": number;
    "draftAttachments": Attachment[] | null;
    "id": string;
    "title": string;
    "pinned": boolean;
    "cwd": string;
    "createdAt": string;
    "updatedAt": string;
    "status": string;
    "error": string;
    "draft": string;
    "messages": Message[] | null;
    "queue": Message[] | null;
    "queuePaused": boolean;
    "interaction": Interaction | null;
    "modelsState": string;
    "modelsError": string;
    "models": Model[] | null;
    "model": string;
    "commands": Command[] | null;
    "searchableText": string;
    "sessionFile": string;
    "provider": string;
}

export interface Settings {
    "shortcut": string;
    "piPath": string;
}

export interface Snapshot {
    "version": number;
    "currentId": string;
    "sessions": (Session | null)[] | null;
    "current": Session | null;
    "settings": Settings;
    "environment": Environment;
    "error": string;
}
